### PR TITLE
misc: support Dart 2 stable

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@mbullington – this is crazy important we get this in soon. See https://medium.com/dartlang/getting-ready-for-dart-2-and-making-your-packages-look-great-on-the-pub-site-118464d7f59d

CC @nex3

**Comment by mbullington** [comment]
Great, thank you for the PR! I'll try to have it up on pub shortly.

**Comment by kevmoo** [comment]
Thanks!

**Comment by kevmoo** [comment]
@mbullington – any way you could get his published soonish? For many of our projects, this is the only package blocking a full test of the Dart 2 shipping version number.

Cheers.

**Comment by mbullington** [comment]
@kevmoo Sorry about the wait, it should now be published on pub. Congrats on Dart 2!

**Comment by kevmoo** [comment]
Thank you!

**Pull request merged**
