### PR TITLE
Fixes for newer Electron builds, release 2.0.1

### PR DESCRIPTION
**Pull request by Mstrodl**

### CODE REVIEW

**Comment by nex3** [comment]
Can you provide a bit more context for this? How does the old way of doing things break? I gather than `global.location =` and `global.document =` does *something* in Electron, but what exactly?

**Comment by Mstrodl** [comment]
@nex3 Sorry, I guess I thought I wrote a description on this PR. Check this out: 
image

Basically, because `self` isn't a "magic" object created by the browser, the `window.location` setter doesn't work...

**Comment by Mstrodl** [comment]
Worth noting: AFAICT, this isn't strictly needed for `document` yet, but I think it's safer to do that now given that it could very easily change / vary by JS engine.

**Comment by Mstrodl** [comment]
Maybe @Awjin or @nex3 could take a look?

**Comment by Mstrodl** [comment]
Maybe @Awjin or @nex3 could take a look?

**Review by nex3 — APPROVED** [review]

**Comment by nex3** [comment]
@mbullington this is ready for publishing

**Comment by Mstrodl** [comment]
@mbullington Hrm, you reacted but it doesn't appear to be actually published? Might be a mistake, I'm not sure. ( https://pub.dev/packages/node_preamble/versions )

**Comment by mbullington** [comment]
My bad, should be published now!

**Pull request merged**
