### PR TITLE
Replace all backslash occurrences in cwd on Windows

### PR DESCRIPTION
**Pull request by dmitrage**
Hi! Currently only the first one is replaced. This fix at least resolves my issue at sass/dart-sass/issues/301

### CODE REVIEW

**Comment by mbullington** [comment]
I'll try to publish on pub sometime today after adding a few other fixes, thanks!

**Comment by nex3** [comment]
@mbullington What's the timeline on publishing this? I'd really like to get a new Dart Sass release that includes the fix out today.

**Comment by mbullington** [comment]
@nex3 node_preamble version 1.4.1 is now on pub.

**Comment by nex3** [comment]
Thanks!

**Pull request merged**
