### PR TITLE
Fix Electron Support

### PR DESCRIPTION
**Pull request by Mstrodl**
This patch should enable Electron renderer processes with `nodeIntegration: true` to work properly.

Background: I was trying to use [the dart-sass project's javascript package](https://npmjs.com/package/sass), but was having issues getting imports to resolve properly because it was trying to load imports relative to `location.href` for some reason. For example: `https://example.org/page.html/path/to/my/local/file.scss`. This patch seems to fix the issue, although I don't entirely understand why.

### CODE REVIEW

**Comment by mbullington** [comment]
Version v1.4.9 just published on pub should fix this issue. Please let me know, thanks!

**Comment by Mstrodl** [comment]
@mbullington The behavior introduced in the new commit is actually literally the opposite of what I'm trying to accomplish

**Comment by mbullington** [comment]
I see... lol, I'm so sorry for misunderstanding the intent of your PR. Fixing now.

**Comment by Mstrodl** [comment]
@mbullington Thank you so much! Sorry!

**Comment by mbullington** [comment]
Sorry about this again, fix is in node_preamble 1.4.10

**Comment by Mstrodl** [comment]
@mbullington Thank you!

**Comment by Mstrodl** [comment]
@mbullington This still doesn't work, the line should have a negated `dartNodeIsActuallyNode`:

```js
  if (!dartNodeIsActuallyNode && dartNodePreambleSelf.process && dartNodePreambleSelf.versions && process.versions.hasOwnProperty('electron') && process.versions.hasOwnProperty('node')) {   
```

**Comment by Mstrodl** [comment]
Actually wait, there's a typo there too,
`dartNodePreambleSelf.versions` => `process.versions`

**Comment by mbullington** [comment]
That's... very embarrassing on my part. Thanks for being so on the ball here, will address immediately.

**Comment by mbullington** [comment]
**Update:** I used the really cool Electron Fiddle to verify that the implementation in `v1.4.12` works. Please take a look, sorry again.

@Mstrodl

**Pull request closed without merging**
