### PR TITLE
Support electron `nodeIntegration:false`

### PR DESCRIPTION
**Pull request by Mstrodl**
When `nodeIntegration:false` under electron, dangerous values aren't available under `global`, they are specified without any qualifiers.

### CODE REVIEW

**Comment by Mstrodl** [comment]
@mbullington Hate to bother you, but could you take a look at this?

**Comment by mbullington** [comment]
Hi @Mstrodl thanks for the mention, I happened to miss this notification.

Will take a look soon!

Thanks.

**Comment by Mstrodl** [comment]
@mbullington I just wanted to follow up about this

**Comment by Mstrodl** [comment]
@mbullington Hi there, I was hoping you could take a look at this?

**Comment by Mstrodl** [comment]
@mbullington Can you please take a look at this?

**Comment by Mstrodl** [comment]
@mbullington Hi there, any chance you could take a look at this? My project has been broken for the past 2 months.

**Review by mbullington — APPROVED** [review]
Think this will work well, thanks!

**Review by mbullington — APPROVED** [review]

**Pull request merged**
